update licenses to current state
Gamify-IT/third-party-license-notice pull request #12
Opened 2023-04-16 19:49 UTC by Gr33ndev

Closes Gamify-IT/issues#500

2023-04-18 11:25 UTC, delvh reviewed
Ouch.
I can finally imagine your pain.

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "MIT", "compName": "de.uni-stuttgart.gamify-it:authentification-validator", "compVersion": "v1.0.0", "copyright": "Copyright (c) 2022 GamifyIT – A Web-based Gaming Platform for Comp
We document our own library? :grin:

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "MIT", "compName": "@types/sockjs-client", "compVersion": "1.5.1", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "MIT", "compName": "@types/sockjs-client", "compVersion": "1.5.1", "copyright": "Copyrights are respective of each contributor listed at the beginning of each definition file.", "copyrightSource": "https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "MIT", "compName": "@types/stompjs", "compVersion": "2.3.5", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "MIT", "compName": "@types/stompjs", "compVersion": "2.3.5", "copyright": "unknown", "copyrightSource": "https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "org.hibernate.validator:hibernate-validator", "compVersion": "8.0.0.Final", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "org.hibernate.validator:hibernate-validator", "compVersion": "8.0.0.Final", "copyright": "unknown", "copyrightSource": "https://github.com/hibernate/hibernate-validator/blob/8.0.0.Final/license.txt"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "com.github.tomakehurst:wiremock", "compVersion": "3.0.0-beta-4", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "com.github.tomakehurst:wiremock", "compVersion": "3.0.0-beta-4", "copyright": "unknown", "copyrightSource": "https://github.com/wiremock/wiremock/blob/3.0.0-beta-4/LICENSE.txt"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "MIT", "compName": "@rushstack/eslint-patch", "compVersion": "1.1.4", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "MIT", "compName": "@rushstack/eslint-patch", "compVersion": "1.1.4", "copyright": "Copyright (c) Microsoft Corporation. All rights reserved.", "copyrightSource": "https://github.com/microsoft/rushstack/blob/main/eslint/eslint-patch/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "MIT", "compName": "@types/highlight.js", "compVersion": "10.1.0", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "MIT", "compName": "@types/highlight.js", "compVersion": "10.1.0", "copyright": "unknown", "copyrightSource": "https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "MIT", "compName": "@types/marked ", "compVersion": "4.0.8", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "MIT", "compName": "@types/marked ", "compVersion": "4.0.8", "copyright": "unknown", "copyrightSource": "https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "@typescript/lib-dom", "compVersion": "npm:@types/web@^0.0.93", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "@typescript/lib-dom", "compVersion": "npm:@types/web@^0.0.93", "copyright": "unknown", "copyrightSource": "https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/%40types/web%400.0.93/LICENSE.txt"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "google-api-core", "compVersion": "2.8.2", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "google-api-core", "compVersion": "2.8.2", "copyright": "unknown", "copyrightSource": "https://github.com/googleapis/python-api-core/blob/v2.8.2/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "google-api-python-client", "compVersion": "2.52.0", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "google-api-python-client", "compVersion": "2.52.0", "copyright": "unknown", "copyrightSource": "https://github.com/googleapis/google-api-python-client/blob/v2.52.0/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "google-auth", "compVersion": "2.9.0", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "google-auth", "compVersion": "2.9.0", "copyright": "unknown", "copyrightSource": "https://github.com/googleapis/google-auth-library-python/blob/v2.9.0/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "google-auth-httplib2", "compVersion": "0.1.0", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "google-auth-httplib2", "compVersion": "0.1.0", "copyright": "unknown", "copyrightSource": "https://github.com/googleapis/google-auth-library-python-httplib2/blob/v0.1.0/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "google-auth-oauthlib", "compVersion": "0.5.2", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "google-auth-oauthlib", "compVersion": "0.5.2", "copyright": "unknown", "copyrightSource": "https://github.com/googleapis/google-auth-library-python-oauthlib/blob/v0.5.2/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "googleapis-common-protos", "compVersion": "1.56.3", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "googleapis-common-protos", "compVersion": "1.56.3", "copyright": "unknown", "copyrightSource": "https://github.com/googleapis/python-api-common-protos/blob/v1.56.3/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "requests", "compVersion": "2.28.1", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "requests", "compVersion": "2.28.1", "copyright": "unknown", "copyrightSource": "https://github.com/psf/requests/blob/v2.28.1/LICENSE"},
```

2023-04-18 11:25 UTC, delvh commented on LicenseNotes.json
> +  {"licTypeName": "Apache-2.0", "compName": "uritemplate", "compVersion": "4.1.1", "copyright": "unknown", "copyrightSource": ""},
```suggestion
  {"licTypeName": "Apache-2.0", "compName": "uritemplate", "compVersion": "4.1.1", "copyright": "unknown", "copyrightSource": "https://github.com/python-hyper/uritemplate/blob/main/LICENSE.APACHE"},
```

2023-04-18 16:53 UTC, robojones requested changes
Towercrush frontend now has two new dependencies with MIT license. Please add:

- https://www.npmjs.com/package/vue3-particles
- https://www.npmjs.com/package/tsparticles

2023-04-25 17:02 UTC, delvh approved these changes

2023-04-26 10:19 UTC, merged